name: farmacia_de_casa
description: "Seu gerenciador de medicamentos pessoal."
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase - Versões mais recentes compatíveis com o core v2
  firebase_core: ^2.27.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7

  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  mobile_scanner: ^7.1.4
  flutter_native_splash: ^2.4.0
  intl: ^0.20.2 
  permission_handler: ^12.0.1

  # Banco de Dados Local (Offline)
  sqflite: ^2.3.0
  path: ^1.9.0
  uuid: ^4.3.3
  
  # Dependências de notificação e data
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  app_settings: ^5.2.0

  # Dependência para escolher imagens
  image_picker: ^1.1.2

  # Dependência para gráficos
  fl_chart: ^1.1.1

  # Dependência para abrir outros apps
  url_launcher: ^6.3.0

  # Dependência para ler contatos
  flutter_contacts: ^1.1.8

  # Dependência para informações do dispositivo
  device_info_plus: ^10.1.0
  
  shared_preferences: ^2.2.3

  # Dependência para compartilhamento (Versão compatível com seu Firebase)
  share_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo_moderno.png
    - assets/login_illustration.png
    - assets/cadastro_illustration.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icone_app.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_moderno.png
